#!/bin/sh

python_dir=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`
module_name="caro"

mkdir -p $python_dir/$module_name
mkdir -p /etc/opt/grid
cp common.* $python_dir/$module_name
touch $python_dir/$module_name/__init__.py
cp config/* /etc/opt/grid
cp carod /usr/sbin
chmod 755 /usr/sbin/carod
chown root.root /usr/sbin/carod
