#!/bin/sh

python_dir=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`
module_name="caro"

rm -rf $python_dir/$module_name
rm -rf /etc/opt/grid
rm -rf /usr/sbin/carod
